/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.brad.project.GUI;

import com.brad.project.ConnectionHandler;
import com.brad.project.Storage;
import com.brad.project.YAMLHandler;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author brad
 */
public class LoginScreen extends javax.swing.JFrame {

    /**
     * Creates new form LoginScreen
     */
    public LoginScreen() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WelcomeTxt1 = new javax.swing.JLabel();
        WelcomeTxt2 = new javax.swing.JLabel();
        CompanyName = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        Login = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        WelcomeTxt1.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        WelcomeTxt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WelcomeTxt1.setText("Company Name:");

        WelcomeTxt2.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        WelcomeTxt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WelcomeTxt2.setText("Email:");

        CompanyName.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N

        Email.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N

        Login.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        Login.setText("Login");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(WelcomeTxt1, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WelcomeTxt2, javax.swing.GroupLayout.DEFAULT_SIZE, 1012, Short.MAX_VALUE)
                    .addComponent(CompanyName)
                    .addComponent(Email, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(410, 410, 410)
                .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(WelcomeTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(WelcomeTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Login)
                .addContainerGap(259, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:
        String company = CompanyName.getText();
        String email = Email.getText();
        ConnectionHandler ch = new ConnectionHandler();
        String check = ch.checkUser(company, email);
        System.out.println(check);
        if(check.split("=")[1].contains("VALID")) {
            Storage.getInstance().current_user_id = email;
            YAMLHandler yamlhandler = new YAMLHandler();
            try {
                yamlhandler.write();
            } catch (IOException ex) {
                Logger.getLogger(LoginScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.dispose();
            new HomeScreen();
        }
        else {
            
        }
    }//GEN-LAST:event_LoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CompanyName;
    private javax.swing.JTextField Email;
    private javax.swing.JButton Login;
    private javax.swing.JLabel WelcomeTxt1;
    private javax.swing.JLabel WelcomeTxt2;
    // End of variables declaration//GEN-END:variables
}
